//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyuiu.DarychevAA.Task1.V4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tyuiu.DarychevAA.Task1.V4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1491254488_chartflexibledatestatstatistics_82950 {
            get {
                object obj = ResourceManager.GetObject("_1491254488_chartflexibledatestatstatistics_82950", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKS
        ///1|Оскар Уайльд|Портрет Дориана Грея|2022|219|True|&quot;&quot;&quot;Портрет Дориана Грея&quot;&quot; — самое знаменитое произведение Оскара Уайльда, единственный его роман, вызвавший в свое время шквал негативных оценок и тем не менее имевший невероятный успех.&quot;|
        ///2|Фрэнсис Ходжсон Бёрнетт|Таинственный сад|2022|269|True|В центре романа «Таинственный сад» – десятилетняя Мери Леннокс, вернувшаяся из Индии в Англию после смерти родителей. |
        ///3|Джейн Остен|Гордость и предубеждение|2022|229|True||
        ///4|Эмили Джейн Бронте|Грозовой п [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_3530 {
            get {
                object obj = ResourceManager.GetObject("document_3530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter_icon_icons_com_64590 {
            get {
                object obj = ResourceManager.GetObject("filter_icon_icons_com_64590", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READERS
        ///1|Смирнов А.А.|Мельникайте 13 кв 23|79129239415|2|23,12,2023 ||
        ///1|Смирнов А.А|Мельникайте 13 кв 23|79129239415|6|12,10,2023 |12,11,2023 |
        ///2|Попов А.Б|Малыгина 13 кв 1|79131254511|6|01,12,2023 ||
        ///3|Сидорова В.Е|Широтная 1 кв 149|79123131541|13|01,03,2024 ||
        ///3|Сидорова В.Е|Широтная 1 кв 149|79123131541|30|01,03,2024 ||
        ///3|Сидорова В.Е|Широтная 1 кв 149|79123131541|29|10,02,2024 ||
        ///4|Малышкина А.Ф.|Республики 152 кв 13|79571751512|15|15,11,2023 |15,11,2023 |
        ///4|Малышкина А.Ф.|Республики 152 кв 13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Readers {
            get {
                return ResourceManager.GetString("Readers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap savetheapplication_guardar_2958 {
            get {
                object obj = ResourceManager.GetObject("savetheapplication_guardar_2958", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap twocirclingarrows1_120592 {
            get {
                object obj = ResourceManager.GetObject("twocirclingarrows1_120592", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
